# permissions for end users to view httpechoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httpecho-viewer-role
rules:
- apiGroups:
  - http.philips.com
  resources:
  - httpechoes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - http.philips.com
  resources:
  - httpechoes/status
  verbs:
  - get
