apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  # Uncomment the below line to create a Headless Service
  # clusterIP: None
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
