apiVersion: v1
kind: Pod
metadata:
  labels:
    run: research
  name: research
spec:
  containers:
  - image: nginx
    name: research
    volumeMounts:
      - mountPath: "/data/app/config"
        name: configpvc
    resources: {}
  volumes:
    - name: configpv
      persistentVolumeClaim:
        claimName: researchpvc
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
