apiVersion: v1
kind: PersistentVolume
metadata:
  name: researchpv
spec:
  capacity:
    storage: 512m
  accessModes:
    - ReadWriteMany
  storageClassName: shared
  hostPath:
    path: /data/config
